# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='/static/img/', width_field='width_field'),
        ),
    ]
