# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160821_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='/media', width_field='width_field'),
        ),
    ]
