# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_no', models.CharField(blank=True, max_length=36, null=True)),
                ('title', models.CharField(max_length=36)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contect', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('faxno', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('invalid', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('line_memo', models.CharField(blank=True, max_length=50, null=True)),
                ('invalid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Product')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user', models.CharField(max_length=60)),
                ('ord_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('invalid', models.BooleanField(default=False)),
                ('memo', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user', models.CharField(max_length=60)),
                ('ord_date', models.DateField()),
                ('customer_title', models.CharField(max_length=60)),
                ('ships_order', models.CharField(max_length=16)),
                ('ord_amount', models.IntegerField(default=1)),
                ('delivery', models.DateField()),
                ('memo', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Product')),
            ],
        ),
        migrations.AddField(
            model_name='quotedetail',
            name='quotehead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.QuoteHead'),
        ),
    ]
