# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_line', models.IntegerField(default=1)),
                ('ord_amount', models.IntegerField(default=1)),
                ('delivery', models.DateField()),
                ('memo', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ShipOrderHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user', models.CharField(max_length=60)),
                ('ord_date', models.DateField()),
                ('customer_title', models.CharField(max_length=60)),
                ('default_delivery', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SaleOrder',
        ),
        migrations.AddField(
            model_name='shiporderdetail',
            name='ships_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.ShipOrderHead'),
        ),
    ]
