# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_auto_20160811_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiporderdetail',
            name='memo',
        ),
        migrations.AddField(
            model_name='shiporderdetail',
            name='line_comment',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='shiporderhead',
            name='head_memo',
            field=models.TextField(default=datetime.datetime(2016, 8, 11, 10, 34, 19, 210482, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
