# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_auto_20160811_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiporderdetail',
            name='unitprice',
            field=models.FloatField(default=1),
        ),
    ]
