# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_quotehead_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotehead',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotehead',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotehead',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotehead',
            name='ord_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
