# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0009_auto_20160818_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotehead',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
